
export const UPDATE_CODE_FIELD = 'UPDATE_CODE_FIELD';
export const CHANGE_CODE_BUTTON = 'CHANGE_CODE_BUTTON';

export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';

export const CHANGE_COMPOSE_MOVE = 'CHANGE_COMPOSE_MOVE';

export const LOAD_GAME_FIELD = 'LOAD_GAME_FIELD';

export const MAKE_STEP = 'MAKE_STEP';
export const RESET_BOARD = 'RESET_BOARD';
export const STEP_BACK = 'STEP_BACK';

export const LOAD_ALGO = 'LOAD_ALGO';
export const PLAY = 'PLAY'
export const PAUSE = 'PAUSE'

export const GENERATE_GAME_FIELD = 'GENERATE_GAME_FIELD';
export const UPDATE_GAME_FIELD = 'UPDATE_GAME_FIELD';

export const GENERATE_CODE_FIELD = 'GENERATE_CODE_FIELD';