export const GENERATE_GAME_FIELD = 'GENERATE_GAME_FIELD';
export const UPDATE_GAME_FIELD = 'UPDATE_GAME_FIELD';
export const GENERATE_CODE_FIELD = 'GENERATE_CODE_FIELD';
export const UPDATE_CODE_FIELD = 'UPDATE_CODE_FIELD';
